# Generated by Django 4.2.4 on 2024-03-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('src', models.URLField(max_length=400)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_link', models.URLField()),
                ('web_link', models.URLField()),
                ('date', models.DateField()),
                ('enterprise', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('technologies', models.ManyToManyField(to='projects.technologyicon')),
            ],
        ),
    ]
