# Generated by Django 4.2.4 on 2024-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='web_link',
            field=models.URLField(null=True),
        ),
    ]
