# Generated by Django 4.2.4 on 2024-03-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_github_link_alter_project_web_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='web_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
