name: Deploy porfolio to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Deployment
      run: |
        ssh -i ${{ secrets.AWS_PORFOLIO_KEY }} ubuntu@${{ secrets.IP_PORFOLIO_AWS }} '
        bash deploy_script.sh
        '

