name: Deploy porfolio to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Deployment
      env: 
        KEY: ${{secrets.AWS_PORFOLIO_KEY}}
        HOST: ${{secrets.IP_PORFOLIO_AWS}}

      run: |
        echo "$KEY" > key && chmod 600 key
        ssh -i key ubuntu@${HOST} '

            bash deploy_script.sh
            '
