name: Deploy porfolio to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Deployment
      env: 
        KEY: ${{ secrets.AWS_PORFOLIO_KEY}}
        USER: ${{ secrets.IP_PORFOLIO_AWS }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ${KEY} ubuntu@${USER} '
          bash deploy_script.sh
          '
